builds:
  - command: test
    flags:
      - -c
    dir: .
    no_main_check: true
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  draft: true
changelog:
  skip: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
